config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = User::BANNED_USERNAMES
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints subdomain: false do
    root 'static#index'
    get '/about', to: 'static#about'
    get '/terms', to: 'static#terms'
    get '/catalogs', to: 'catalog#index'
    get '/catalogs/:id', to: 'catalog#users_by_school', as: "catalogs_by_school"
    ############
    get '/lenta', to: 'admin/posts#index', as: "lenta"
    post '/lenta', to: 'admin/posts#create'
    get '/lentas/:id', to: 'admin/posts#show', as: "lenta_post"
    patch '/lentas/:id', to: 'admin/posts#update'
    delete '/lentas/:id', to: 'admin/posts#destroy'
    get '/lentas/:id/edit', to: 'admin/posts#edit', as: "edit_lenta_post"
    get '/lenta/new', to: 'admin/posts#new', as: "new_lenta_post"
  end

  constraints subdomain: false do
    devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
    as :user do
      get 'users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post 'users/sign_in' => 'devise/sessions#create', :as => :user_session
    end
    delete '/users_avatar', to: 'profile#delete_avatar', as: "delete_avatar"
    delete 'users_background_image', to: "profile#delete_background_image", as: "delete_background_image"
  end
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy"
  end

  constraints SubdomainConstraint do
    get '/', to: 'profile#index', as: "root_user"
    resources :photos
    resources :posts
    end
end

app/views/shared/_infobox.html.haml
= render partial: "shared/time_ago", locals: {post: post}
.infobox
  %span.shared_and_options
    %script{:charset => "utf-8", :src => "//yastatic.net/share/share.js", :type => "text/javascript"}
    %span.yashare-auto-init{"data-yasharel10n" => "ru", "data-yasharequickservices" => "vkontakte,facebook,twitter,odnoklassniki,moimir", "data-yasharetheme" => "counter", "data-yasharetype" => "small"}
  - if user_signed_in?
    - if request.subdomain.blank?
      - if current_user.admin?
        %span
          = link_to 'Изменить', edit_lenta_post_path(post), class: "btn btn-link btn-xs"
          = link_to 'Удалить', lenta_post_path(post), :method => :delete, :data => { :confirm => 'Вы уверены' }, class: "btn btn-link btn-xs"
    - else
      %span
        = link_to 'Изменить', edit_post_path(post), class: "btn btn-link btn-xs"
        = link_to 'Удалить', post_path(post), :method => :delete, :data => { :confirm => 'Вы уверены' }, class: "btn btn-link btn-xs"

app/views/shared/_time_ago.html.haml
.time_ago
  = I18n.l post.created_at, format: "%d %b %Y, %H:%M"