config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = User::BANNED_USERNAMES
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints subdomain: false do
    root 'static#index'
    get '/about', to: 'static#about'
    get '/terms', to: 'static#terms'
    get '/catalogs', to: 'catalog#index'
    get '/catalogs/:id', to: 'catalog#users_by_school', as: "catalogs_by_school"
    ############
    get '/lenta', to: 'admin/posts#index', as: "lenta"
    post '/lenta', to: 'admin/posts#create'
    get '/lentas/:id', to: 'admin/posts#show', as: "lenta_post"
    patch '/lentas/:id', to: 'admin/posts#update'
    delete '/lentas/:id', to: 'admin/posts#destroy'
    get '/lentas/:id/edit', to: 'admin/posts#edit', as: "edit_lenta_post"
    get '/lenta/new', to: 'admin/posts#new', as: "new_lenta_post"
  end

  constraints subdomain: false do
    devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
    as :user do
      get 'users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post 'users/sign_in' => 'devise/sessions#create', :as => :user_session
    end
    delete '/users_avatar', to: 'profile#delete_avatar', as: "delete_avatar"
    delete 'users_background_image', to: "profile#delete_background_image", as: "delete_background_image"
  end
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy"
  end

  constraints SubdomainConstraint do
    get '/', to: 'profile#index', as: "root_user"
    resources :photos
    resources :posts
    end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
    @citys = City.more_zero_schools
    @users = User.order(created_at: :desc).limit(25)
  end

  def users_by_school
    @school = School.find(params[:id])
    @users = @school.users.sort_by {|u| -u.calculate_the_rating }
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/_users.html.haml
- users.each do |user|
  = link_to root_user_url(subdomain: user.username) do
    .user_l
      = image_tag user.avatar.url(:small), class: "img-rounded user_avatar_l"
      .name
        = user.last_name
        = user.first_name
        = user.middle_name
        .rating
          Рейтинг
          = "%4.1f" % user.calculate_the_rating

app/views/catalog/index.html.haml
- content_for(:title) do
  Каталог
- content_for(:data_no_turbolink) do
  true

.container.box(style="max-width: 1020px; padding: 15px 25px 30px 25px; margin-top: 17px;")
  .catalog
    %center
      %h1 Каталог
      %p Здесь вы можете найти любого учителя
    .row
      .col-md-7
        %h3 Поиск по городу
        .panel-group#accordion(role="tablist" aria-multiselectable="true")
          %ul
            - @citys.each do |c|
              - if !c.schools.empty?
                %li.city_l(id="#{c.full_name}")
                  %b
                    %a.city_l(role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_#{c.id}" aria-expanded="true" aria-controls="collapse_#{c.id}")= c.full_name
                    %a(name="#{c.name}")
                  .h
                  %div(id="collapse_#{c.id}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne")
                    %ul(id="#{c.full_name}")
                      - c.schools.each do |s|
                        %li(id="#{s.id}")= link_to s.name, catalogs_by_school_url(id: s.id)
      .col-md-5
        %h3 Новые пользователи
        = render partial: "catalog/users", locals: {users: @users}

app/views/catalog/users_by_school.html.haml
- content_for(:title) do
  = @school.name

.container.box(style="max-width: 1020px; padding: 15px 25px 30px 25px; margin-top: 17px;")
  .catalog
    = link_to "Школы", catalogs_url
    >
    %b= @school.name
    .h
    - if !@users.empty?
      %ul
        = render partial: "catalog/users", locals: {users: @users}

    - else
      %center(style="padding: 45px;")
        %h3 Никто из #{@school.name} не зарегистрировался
        = link_to "Вернутся в каталог", catalogs_url