config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = User::BANNED_USERNAMES
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints subdomain: false do
    root 'static#index'
    get '/about', to: 'static#about'
    get '/terms', to: 'static#terms'
    get '/catalogs', to: 'catalog#index'
    get '/catalogs/:id', to: 'catalog#users_by_school', as: "catalogs_by_school"
    ############
    get '/lenta', to: 'admin/posts#index', as: "lenta"
    post '/lenta', to: 'admin/posts#create'
    get '/lentas/:id', to: 'admin/posts#show', as: "lenta_post"
    patch '/lentas/:id', to: 'admin/posts#update'
    delete '/lentas/:id', to: 'admin/posts#destroy'
    get '/lentas/:id/edit', to: 'admin/posts#edit', as: "edit_lenta_post"
    get '/lenta/new', to: 'admin/posts#new', as: "new_lenta_post"
  end

  constraints subdomain: false do
    devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
    as :user do
      get 'users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post 'users/sign_in' => 'devise/sessions#create', :as => :user_session
    end
    delete '/users_avatar', to: 'profile#delete_avatar', as: "delete_avatar"
    delete 'users_background_image', to: "profile#delete_background_image", as: "delete_background_image"
  end
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy"
  end

  constraints SubdomainConstraint do
    get '/', to: 'profile#index', as: "root_user"
    resources :photos
    resources :posts
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, :user, presence: true

  def previous
    self.class.where("id > ?", id).first
  end

  def next
    self.class.where("id < ?", id).last
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  include PostMethods

  before_action :tenant_switch_public
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :user_have_access?, except: [:index, :show]

  layout "sub"

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to lenta_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to lenta_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to lenta_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def user_have_access?
      if user_signed_in? && current_user.admin?
        true
      else
        redirect_to lenta_path, alert: "У Вас недостаточно прав, авторизуйтесь или зарегистрируйтесь"
      end
    end

    def tenant_switch_public
      logger.info("!!!Apartment current tenant is #{Apartment::Tenant.current}!!!")
      Apartment::Tenant.switch!(Apartment::Tenant.default_tenant)
      logger.info("!!!Apartment switch tenant to #{Apartment::Tenant.current}!!!")
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostMethods

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :user_have_access?, except: [:index, :show]

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def user_have_access?
      if user_signed_in? && current_user == User.find_by_username(request.subdomain)
        true
      else
        redirect_to posts_path, alert: "У Вас недостаточно прав, авторизуйтесь или зарегистрируйтесь"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
- content_for(:data_no_turbolink) do
  true

= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.text_field :title, placeholder: "Название", class: "form-control"
  .form-group
    = f.label :body, style: "display: none;r"
    = f.text_area :body, class: "wysihtml5 form-control", id: "some-textarea", rows: 30
  .form-group
    = f.submit 'Сохранить', class: "btn btn-default"

app/views/posts/_post.html.haml
.post_item
  %h3
    = link_to post.title, post_path(post), class: "link"

  = render partial: "shared/time_ago", locals: {post: post}

app/views/posts/edit.html.haml
.container.box
  %h1
    Изменить запись
    .pull-right= link_to 'Удалить', @post, :method => :delete, :data => { :confirm => 'Вы уверены' }, class: "btn btn-xs btn-danger"

  = render 'form'

  = link_to 'Просмотреть', @post

app/views/posts/index.html.haml
-# - content_for(:title) do
-#   = @user.first_name
-#   = @user.last_name
-#   \|
-#   Блог

.box
  - if @posts.count != 0
    .posts_box
      %h1.main_posts_h
        Блог
        - if has_user_access?
          = link_to new_post_path, class: "btn btn-default btn-smarty" do
            Добавить запись
            %span.glyphicon.glyphicon-plus
    #my-posts
      = render @posts
    #infinite-scrolling
      = will_paginate

  - else
    %center
      - if has_user_access?
        .warning(style="margin-top: 35px")
          %p
            %b У вас пока нет записей в блоге
          = link_to new_post_path, class: "btn btn-link btn-lg" do
            Добавить запись
      - else
        .warning(style="margin-top: 35px")
          %p
            %b
              У #{@user.first_name} #{@user.last_name} пока нет записей в блоге

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.haml
.container.box
  %h1 Новая запись

  = render 'form'

app/views/posts/show.html.haml
- content_for(:title) do
  = @post.title
  
- content_for(:description) do
  = sanitize strip_tags @post.body

.container.box(style="margin-top: 15px; padding: 35px; padding-top: 14px;")
  .post
    %h1
      = @post.title

    = render partial: 'shared/infobox.html', locals: {post: @post}
    .body
      = sanitize @post.body
    = render partial: 'shared/infobox.html', locals: {post: @post}

    - disqus_thread @post.id