config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = User::BANNED_USERNAMES
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints subdomain: false do
    root 'static#index'
    get '/about', to: 'static#about'
    get '/terms', to: 'static#terms'
    get '/catalogs', to: 'catalog#index'
    get '/catalogs/:id', to: 'catalog#users_by_school', as: "catalogs_by_school"
    ############
    get '/lenta', to: 'admin/posts#index', as: "lenta"
    post '/lenta', to: 'admin/posts#create'
    get '/lentas/:id', to: 'admin/posts#show', as: "lenta_post"
    patch '/lentas/:id', to: 'admin/posts#update'
    delete '/lentas/:id', to: 'admin/posts#destroy'
    get '/lentas/:id/edit', to: 'admin/posts#edit', as: "edit_lenta_post"
    get '/lenta/new', to: 'admin/posts#new', as: "new_lenta_post"
  end

  constraints subdomain: false do
    devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
    as :user do
      get 'users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post 'users/sign_in' => 'devise/sessions#create', :as => :user_session
    end
    delete '/users_avatar', to: 'profile#delete_avatar', as: "delete_avatar"
    delete 'users_background_image', to: "profile#delete_background_image", as: "delete_background_image"
  end
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy"
  end

  constraints SubdomainConstraint do
    get '/', to: 'profile#index', as: "root_user"
    resources :photos
    resources :posts
    end
end

app/views/layouts/_flash.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissible(role="alert")
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = flash[:notice]
- if flash[:alert]
  .alert.alert-warning.alert-dismissible(role="alert")
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = flash[:alert]
- if flash[:error]
  .alert.alert-danger.alert-dismissible(role="alert")
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = flash[:error]

app/views/layouts/_footer.html.haml
%footer(style="margin-top: 35px;")
  = link_to "главная", root_url(subdomain: false), class: "btn btn-link btn-sm"
  = link_to "о сайте", about_url(subdomain: false), class: "btn btn-link btn-sm"
  = link_to "правила", terms_url(subdomain: false), class: "btn btn-link btn-sm"
  %br
  = link_to "tchr.ru", root_url(subdomain: false), style: "color: #333;"
  &copy;
  = Time.now.year

  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-66932258-1', 'auto');
    ga('send', 'pageview');

  / Google Tag Manager
  %noscript
    %iframe{:height => "0", :src => "//www.googletagmanager.com/ns.html?id=GTM-W6QF7R", :style => "display:none;visibility:hidden", :width => "0"}
  :javascript
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-W6QF7R');
  / End Google Tag Manager

app/views/layouts/_meta.html.haml
- if content_for?(:description)
  %meta{name: "description", content: yield(:description)}
- else
  - if !request.subdomain.empty?
    %meta{name: "description", content: @user.about}
  - else
    %meta{name: "description", content: "tchr.ru - интернет-ресурс, который помогает учителям поддерживать связь с Учениками и Коллегами, а репетиторам, находить новых учеников. tchr.ru – это сетевой проект для учителей и репетиторов, позволяющий создать личный сайт."}



%meta{name: "keywords", content: "Сайт для учителей, Конструктор сайтов для учителей, Конструктор сайтов, Конструктор сайтов для репетиторов, Сайт для Репетиторов, Найти учителя, Найти репетитора"}


= favicon_link_tag "/apple-icon-57x57.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-60x60.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-72x72.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-76x76.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-114x114.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-120x120.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-144x144.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-152x152.png", :rel => "apple-touch-icon"
= favicon_link_tag "/apple-icon-180x180.png", :rel => "apple-touch-icon"
= favicon_link_tag "/android-icon-192x192.png", :rel => "icon", :type => "image/png"
= favicon_link_tag "/favicon-32x32.png", :rel => "icon", :type => "image/png"
= favicon_link_tag "/favicon-96x96.png", :rel => "icon", :type => "image/png"
= favicon_link_tag "/favicon-16x16.png", :rel => "icon", :type => "image/png"
= favicon_link_tag "/manifest.json", :rel => "manifest"
%meta{:content => "#ffffff", :name => "msapplication-TileColor"}/
%meta{:content => "#ffffff", :name => "theme-color"}/

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.my-nav-1
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_url(subdomain: false), style: "padding: 3px; 5px 0 10px; margin-left: 10px;", class: "navbar-brand" do
        = image_tag "logo.png", class: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if request.subdomain != ""
          - user = User.find_by_username(request.subdomain)
          %li= link_to user.first_name+" "+user.last_name, root_user_path, class: "username"
          %li= link_to "Фотографии", photos_path
          %li= link_to "Блог", posts_path
        - else
          %li= link_to "tchr.ru", root_path, class: "logo"
      -# %form.navbar-form.navbar-left{:role => "search"}
      -#   .form-group
      -#     %input.form-control{:placeholder => "Search", :type => "text"}/
      -#   %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Учителя", catalogs_url(subdomain: false)
        %li= link_to "Новости образования", lenta_url(subdomain: false)
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.username
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Профиль", root_user_url(subdomain: current_user.username)
              %li= link_to "Настройки", edit_user_registration_url(subdomain: false)
              %li.divider{:role => "separator"}
              %li= link_to "Выйти", sign_out_path, method: :delete
        - else
          %li= link_to "Войти", new_user_session_url(subdomain: false)
          %li= link_to "Создать свой сайт", new_user_registration_url(subdomain: false), class: "btn btn-default btn-smarty", style: "padding: 8px; margin-top: 6px; margin-left: 5px;"

app/views/layouts/application.html.haml
!!! 5
%html(lang="ru")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = render partial: "layouts/meta"
    %title
      - if content_for?(:title)
        = yield(:title)
        \|
        tchr.ru
      - else
        tchr.ru
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "https://js.stripe.com/v1/"
    = javascript_include_tag "application"
    = disqus_init
    = yield(:head)

    - if !request.subdomain.empty? || controller.controller_name == 'registrations'
      - case @user.background_fixed
      - when -1
        - @fixed = "left"
      - when 0
        - @fixed = "center"
      - when 1
        - @fixed = "right"
      :css
        body {
          background-color: #{@user.background_color};
          background-image: url(#{@user.background_image.url});
          background-repeat: no-repeat;
          background-position: top #{@fixed};
          background-attachment: #{"fixed" if @user.background_attachment};
        }


  %body(data-no-turbolink="#{content_for?(:data_no_turbolink) ? yield(:data_no_turbolink) : 'false'}")
    = render partial: "layouts/navbar"
    .container
      = render partial: "layouts/flash"

    .container
      = yield
    .container.footer
      = render partial: "layouts/footer"

app/views/layouts/sub.html.haml
!!! 5
%html(lang="ru")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = render partial: "layouts/meta"
    %title
      - if  content_for?(:title)
        = yield(:title)
        \|
        tchr.ru
      - else
        tchr.ru
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "https://js.stripe.com/v1/"
    = javascript_include_tag "application"
    = disqus_init


  %body.sub(data-no-turbolink="#{content_for?(:data_no_turbolink) ? yield(:data_no_turbolink) : 'false'}")
    = render partial: "layouts/navbar"
    .container
      = render partial: "layouts/flash"

    = yield

    = render partial: "layouts/footer"